server {
    listen 443 ssl;
    server_name api.bookent.shop;

    ssl_certificate /etc/letsencrypt/live/api.bookent.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.bookent.shop/privkey.pem;

    location / {
        proxy_pass http://server:3000;
    }
}


server {
    listen 80;
    location / {
        proxy_pass http://server:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
